create table penduduk (
	id INT,
	id_penduduk VARCHAR(50),
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	gender VARCHAR(50),
	address VARCHAR(50),
	city VARCHAR(50),
	email VARCHAR(50)
);
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (1, '9928334544', 'Mahala', 'Shaddock', 'Male', '4917 Jackson Court', 'Cardal', 'mshaddock0@skype.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (2, '8744483139', 'Stavros', 'MacAlpine', 'Female', '39690 Farragut Road', 'Arlington', 'smacalpine1@themeforest.net');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (3, '3797264712', 'Bartholomeo', 'Athey', 'Female', '03060 Ramsey Drive', 'Korsakovo', 'bathey2@devhub.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (4, '9314445690', 'Celeste', 'Dugmore', 'Male', '76873 Scott Way', 'Turus', 'cdugmore3@psu.edu');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (5, '9861496912', 'Eliza', 'Smallpeice', 'Male', '078 Bonner Court', 'Tianhe', 'esmallpeice4@tumblr.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (6, '5796372920', 'Evvie', 'Clemoes', 'Female', '2 Almo Point', 'Finspång', 'eclemoes5@state.gov');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (7, '4796082867', 'Tyler', 'Goodinge', 'Male', '31 Harper Lane', 'Oliveira', 'tgoodinge6@51.la');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (8, '3613856964', 'Oralia', 'Archbald', 'Female', '275 Blackbird Lane', 'Welkom', 'oarchbald7@apple.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (9, '4253822290', 'Agnes', 'Rothert', 'Male', '624 Drewry Center', 'Shaxi', 'arothert8@wordpress.org');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (10, '7031820472', 'Maegan', 'Jonuzi', 'Male', '27 Roxbury Terrace', 'Queimados', 'mjonuzi9@apache.org');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (11, '2183390972', 'Meredith', 'McGinny', 'Female', '2 Troy Alley', 'Kabalo', 'mmcginnya@yahoo.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (12, '2662506350', 'Saunder', 'Lawlance', 'Female', '75664 Everett Alley', 'Xin’an', 'slawlanceb@wsj.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (13, '8914872408', 'Earle', 'Benterman', 'Male', '74117 Pierstorff Parkway', 'Racławice', 'ebentermanc@smh.com.au');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (14, '4007884528', 'Terrijo', 'Shervington', 'Female', '92 Dwight Center', 'Tumpang', 'tshervingtond@goodreads.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (15, '3223942106', 'Oralia', 'Card', 'Male', '2125 Loeprich Drive', 'Griboyedov', 'ocarde@imgur.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (16, '0215634438', 'Isabelle', 'Stroder', 'Male', '7 Susan Crossing', 'Bor', 'istroderf@surveymonkey.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (17, '6069836766', 'Jerome', 'Van Ross', 'Female', '22379 Everett Parkway', 'Beaufort', 'jvanrossg@angelfire.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (18, '9438543864', 'Ross', 'Dunseath', 'Female', '756 Orin Parkway', 'Moulay Yacoub', 'rdunseathh@pen.io');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (19, '3650646676', 'Lebbie', 'Gladeche', 'Female', '1933 Lakewood Drive', 'Giade', 'lgladechei@gnu.org');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (20, '7436295152', 'Sonny', 'Chittim', 'Female', '16412 Muir Point', 'Beauvais', 'schittimj@thetimes.co.uk');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (21, '3786011206', 'Anatollo', 'Cocksedge', 'Female', '914 Charing Cross Alley', 'Moulay Abdallah', 'acocksedgek@csmonitor.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (22, '3373595630', 'Karlens', 'Wilcocks', 'Female', '22507 Upham Lane', 'Stockholm', 'kwilcocksl@chronoengine.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (23, '2553232012', 'Kath', 'Tie', 'Male', '584 Pleasure Drive', 'Laguna Limpia', 'ktiem@bbb.org');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (24, '6888746852', 'Melinde', 'Corday', 'Male', '5704 Hoepker Junction', 'Daleman', 'mcordayn@altervista.org');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (25, '8717499291', 'Arlee', 'Line', 'Male', '41 Schiller Trail', 'Bayrachky', 'alineo@addtoany.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (26, '2980763756', 'Natka', 'Jeanneau', 'Female', '60041 Ryan Hill', 'Sriwing', 'njeanneaup@nymag.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (27, '1799830675', 'Zachery', 'Lugden', 'Male', '6 Schurz Drive', 'Concepción', 'zlugdenq@xrea.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (28, '4844162012', 'Falito', 'Monsey', 'Male', '460 John Wall Circle', 'Ea Drăng', 'fmonseyr@artisteer.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (29, '5902194350', 'Courtenay', 'Fripp', 'Male', '179 Havey Place', 'Krajan Tambakrejo', 'cfripps@dropbox.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (30, '9537404412', 'Lenard', 'D''Ugo', 'Female', '61483 Bonner Road', 'Montélimar', 'ldugot@photobucket.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (31, '0557421071', 'Nelia', 'Douthwaite', 'Female', '1 Bluejay Plaza', 'Magsalangi', 'ndouthwaiteu@domainmarket.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (32, '0765052245', 'Kiley', 'Piff', 'Male', '43 Stuart Junction', 'Compiègne', 'kpiffv@imgur.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (33, '8130854678', 'Norry', 'Rault', 'Female', '32 Arapahoe Hill', 'Parry Sound', 'nraultw@dion.ne.jp');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (34, '3046958471', 'Corbie', 'Prinnett', 'Male', '2978 Emmet Center', 'Ndofane', 'cprinnettx@biglobe.ne.jp');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (35, '7864363806', 'Brier', 'Joint', 'Female', '7 7th Road', 'Ostankinskiy', 'bjointy@time.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (36, '2766558144', 'Shalom', 'Nuccii', 'Female', '87 Graceland Court', 'Tommot', 'snucciiz@tuttocitta.it');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (37, '6983179943', 'Otis', 'McQuilty', 'Female', '0 Almo Road', 'Ruzhany', 'omcquilty10@slideshare.net');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (38, '1063827655', 'Wenona', 'Wiszniewski', 'Female', '95227 Walton Court', 'Mora', 'wwiszniewski11@google.com.au');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (39, '2858317348', 'Benetta', 'Mellings', 'Male', '56501 5th Point', 'Tríkeri', 'bmellings12@is.gd');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (40, '4174114463', 'Shelden', 'Walklot', 'Male', '03998 Pearson Alley', 'Villa Carlos Paz', 'swalklot13@360.cn');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (41, '9899727628', 'Libby', 'Yelding', 'Male', '7 Elgar Circle', 'Shaxi', 'lyelding14@earthlink.net');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (42, '4216440436', 'Jacquenetta', 'Hansard', 'Female', '81139 Moland Crossing', 'Nong Yasai', 'jhansard15@amazon.co.uk');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (43, '0237970449', 'Clyde', 'Doog', 'Male', '832 Schiller Crossing', 'Yukuhashi', 'cdoog16@simplemachines.org');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (44, '3598478933', 'Joletta', 'Fearey', 'Female', '29 Waywood Lane', 'Manquiring', 'jfearey17@indiegogo.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (45, '9539007836', 'Ruben', 'Cordle', 'Female', '1 Cody Court', 'Kaiyuan', 'rcordle18@netvibes.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (46, '2988600090', 'Darla', 'Cuniffe', 'Female', '21463 Roxbury Park', 'Drammen', 'dcuniffe19@booking.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (47, '2563961459', 'Andi', 'McCafferty', 'Male', '027 Mallory Point', 'Agraharam', 'amccafferty1a@comcast.net');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (48, '2009988817', 'Roana', 'Sopp', 'Male', '68 Waxwing Street', 'Pengbu', 'rsopp1b@hc360.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (49, '3221205422', 'Sena', 'Ledgerton', 'Female', '1 Annamark Avenue', 'Kommunar', 'sledgerton1c@statcounter.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (50, '1041970714', 'Hilario', 'Lomaz', 'Female', '332 Stone Corner Center', 'Trondheim', 'hlomaz1d@freewebs.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (51, '3601095807', 'Boot', 'Mebius', 'Female', '5579 Carberry Crossing', 'Carmen', 'bmebius1e@google.com.br');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (52, '0178622338', 'Claudine', 'Grisewood', 'Male', '904 Ridgeview Point', 'Zhaiwu', 'cgrisewood1f@themeforest.net');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (53, '3358111172', 'Julienne', 'Helling', 'Male', '198 Manley Lane', 'Sirte', 'jhelling1g@reuters.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (54, '3507566796', 'Tine', 'Saxelby', 'Male', '835 Pond Plaza', 'Ishige', 'tsaxelby1h@time.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (55, '5241259651', 'Hazlett', 'Purvey', 'Male', '40101 Gale Terrace', 'Sofádes', 'hpurvey1i@senate.gov');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (56, '5784071564', 'Ignatius', 'Drane', 'Male', '8497 Petterle Court', 'Tānk', 'idrane1j@telegraph.co.uk');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (57, '4680789883', 'Sebastiano', 'Thurnham', 'Female', '68 Tony Place', 'Susoh', 'sthurnham1k@loc.gov');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (58, '5577673054', 'Farly', 'Hughson', 'Female', '9 Coolidge Parkway', 'Lorino', 'fhughson1l@artisteer.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (59, '5901762851', 'Marysa', 'Cockaday', 'Female', '2367 Brown Point', 'Barg-e Matāl', 'mcockaday1m@gravatar.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (60, '7248390011', 'Beverly', 'Iacovozzo', 'Male', '49157 Dovetail Way', 'Brody', 'biacovozzo1n@china.com.cn');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (61, '1126532436', 'Rosemonde', 'Gaskarth', 'Female', '7371 Esker Terrace', 'Jakartovice', 'rgaskarth1o@apache.org');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (62, '2335034065', 'Shelba', 'Kerton', 'Male', '3353 Harbort Drive', 'Cholpon-Ata', 'skerton1p@merriam-webster.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (63, '7320406896', 'Valida', 'Dreinan', 'Female', '15 Rieder Point', 'Van Nuys', 'vdreinan1q@tripod.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (64, '0791539644', 'Ainsley', 'Castanares', 'Male', '515 Daystar Place', 'Semibratovo', 'acastanares1r@sogou.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (65, '6058746892', 'Lotti', 'Nowell', 'Female', '1 Dottie Trail', 'Maiorca', 'lnowell1s@cnbc.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (66, '5308525021', 'Carlos', 'Deverille', 'Male', '065 Anniversary Center', 'Uvarovo', 'cdeverille1t@oaic.gov.au');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (67, '6914682747', 'Chaunce', 'Rabjohns', 'Female', '04718 Coolidge Trail', 'Fengyan', 'crabjohns1u@nsw.gov.au');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (68, '3594527719', 'Georgianne', 'Beckles', 'Male', '6302 Summer Ridge Center', 'Gävle', 'gbeckles1v@51.la');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (69, '6020477711', 'Lorrie', 'McNeish', 'Male', '960 Grayhawk Terrace', 'Shijiao', 'lmcneish1w@google.com.hk');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (70, '6085142463', 'Dionis', 'Coopper', 'Female', '2 Hanson Road', 'Fulnek', 'dcoopper1x@eventbrite.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (71, '8647045718', 'Margi', 'Balnaves', 'Female', '7796 Butterfield Center', 'Moganshan', 'mbalnaves1y@amazonaws.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (72, '6631613639', 'Molli', 'Boughton', 'Male', '2 Brentwood Road', 'Manaloal', 'mboughton1z@apple.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (73, '0278519377', 'Myca', 'McCerery', 'Male', '2940 Meadow Valley Center', 'Guanzhuang', 'mmccerery20@vimeo.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (74, '0335547346', 'Willey', 'McLanachan', 'Male', '28 Debra Court', 'Shibganj', 'wmclanachan21@google.es');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (75, '4800426375', 'Godfry', 'Durn', 'Male', '89 Sloan Way', 'Taocun', 'gdurn22@mapy.cz');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (76, '6197670445', 'Davidde', 'Treacher', 'Male', '2267 Ludington Hill', 'Pasian', 'dtreacher23@nationalgeographic.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (77, '0822866218', 'Raymund', 'Thunders', 'Female', '5727 Bay Court', 'Kakegawa', 'rthunders24@weebly.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (78, '4029950272', 'Baxie', 'Bellanger', 'Female', '605 Myrtle Lane', 'Kampinos', 'bbellanger25@theguardian.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (79, '1227823894', 'Edd', 'Robe', 'Male', '9 Sundown Point', 'Hongyansi', 'erobe26@123-reg.co.uk');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (80, '4320588959', 'Elihu', 'Aslin', 'Male', '826 Coleman Court', 'Lincoln', 'easlin27@cam.ac.uk');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (81, '6325360346', 'Kaela', 'Eldritt', 'Female', '08 Vidon Junction', 'Ruoqiang', 'keldritt28@springer.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (82, '3546032535', 'Dennie', 'Tukely', 'Female', '12 Eagle Crest Lane', 'Usman’', 'dtukely29@tripod.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (83, '2096649021', 'Lowrance', 'Mawdsley', 'Female', '3 Dennis Point', 'Toyós', 'lmawdsley2a@nature.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (84, '3749369801', 'Ofella', 'Nottram', 'Male', '0799 Pawling Crossing', 'Piran', 'onottram2b@themeforest.net');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (85, '1162089008', 'David', 'Mation', 'Female', '1 Del Mar Lane', 'Odawara', 'dmation2c@ibm.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (86, '1737019418', 'Aleda', 'Belone', 'Female', '77 Burning Wood Center', 'Jinchuan', 'abelone2d@addthis.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (87, '5274547044', 'Windy', 'Willerstone', 'Female', '82461 Hollow Ridge Court', 'Saparua', 'wwillerstone2e@whitehouse.gov');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (88, '1584562315', 'Betteanne', 'Spensley', 'Male', '4005 Sloan Avenue', 'Bom Despacho', 'bspensley2f@com.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (89, '3018185234', 'Brittney', 'Harverson', 'Female', '35197 Sherman Plaza', 'Rerawere', 'bharverson2g@army.mil');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (90, '9614178841', 'Shirl', 'Bockman', 'Male', '58682 Warbler Way', 'Cacoal', 'sbockman2h@jiathis.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (91, '2581176008', 'Garrett', 'Fannin', 'Male', '81392 Goodland Crossing', 'Krajan', 'gfannin2i@soup.io');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (92, '1314399268', 'Martguerita', 'Delacoste', 'Male', '721 Drewry Street', 'Klembivka', 'mdelacoste2j@irs.gov');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (93, '8012969270', 'Valentin', 'Dockrell', 'Female', '303 Sunnyside Trail', 'Pule', 'vdockrell2k@scientificamerican.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (94, '3916993151', 'Vinny', 'Spreckley', 'Male', '12 Stoughton Terrace', 'Vaiamonte', 'vspreckley2l@google.ru');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (95, '5723392239', 'Loise', 'Hainey', 'Male', '790 La Follette Lane', 'Polen', 'lhainey2m@cdc.gov');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (96, '6938985472', 'Linet', 'Kaas', 'Male', '195 Dixon Circle', 'Wensu', 'lkaas2n@csmonitor.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (97, '9463973311', 'Frazier', 'Sydall', 'Female', '9 Katie Park', 'Kälviä', 'fsydall2o@forbes.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (98, '5309329722', 'Burnard', 'MacNelly', 'Female', '14 Hooker Park', 'Bayan Hure', 'bmacnelly2p@wisc.edu');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (99, '8465412936', 'Melodee', 'Leftbridge', 'Female', '0 Mifflin Junction', 'Bayshint', 'mleftbridge2q@wp.com');
insert into penduduk (id, id_penduduk, first_name, last_name, gender, address, city, email) values (100, '4154280147', 'Major', 'Yurin', 'Female', '23573 Fuller Point', 'Xiaoying', 'myurin2r@liveinternet.ru');
